-- Insertar datos en la tabla 'CATEGORIAS'
INSERT INTO CATEGORIAS (Nombre) VALUES
('Serie'),
('Película');

-- Insertar datos en la tabla 'ACTORES' 

INSERT INTO ACTORES (Nombre) VALUES
('Pedro Pascal'),
('Carl Weathers'),
('Misty Rosas'),
('Chris Bartlett'),
('Rio Hackford'),
('Giancarlo Esposito'),
('Tom Hopper'),
('David Castañeda'),
('Emmy Raver-Lampman'),
('Robert Sheehan'),
('Aidan Gallagher'),
('Elliot Page'),
('Anya Taylor-Joy'),
('Thomas Brodie-Sangster'),
('Harry Melling'),
('Moses Ingram'),
('Chloe Pirrie'),
('Janina Elkin'),
('Lili Reinhart'),
('Casey Cott'),
('Camila Mendes'),
('Marisol Nichols'),
('Madelaine Petsch'),
('Mädchen Amick'),
('Claire Fox'),
('Olivia Colman'),
('Matt Smith'),
('Tobias Menzies'),
('Vanesa Kirby'),
('Helena Bonham Carter'),
('Millie Bobby Brown'),
('Henry Cavill'),
('Sam Claflin'),
('Louis Partridge'),
('Adeel Akhtar'),
('Joaquin Phoenix'),
('Robert De Niro'),
('Zazie Beetz'),
('Frances Conroy'),
('Brett Cullen'),
('Shea Whigham'),
('Robert Downey Jr.'),
('Chris Evans'),
('Mark Ruffalo'),
('Chris Hemsworth'),
('Scarlett Johansson'),
('Jeremy Renner'),
('Emilia Clarke'),
('Lena Headey'),
('Sophie Turner'),
('Kit Harington'),
('Peter Dinklage'),
('Nikolaj Coster-Waldau'),
('Grant Gustin'),
('Carlos Valdes'),
('Danielle Panabaker'),
('Candice Patton'),
('Jesse L. Martin'),
('Tom Cavanagh'),
('Jim Parsons'),
('Johnny Galecki'),
('Kaley Cuoco'),
('Simon Helberg'),
('Kunal Nayyar'),
('Melissa Rauch'),
('Mayim Bialik'),
('Jennifer Aniston'),
('Courteney Cox'),
('Lisa Kudrow'),
('David Schwimmer'),
('Matthew Perry'),
('Matt LeBlanc'),
('Amybeth McNulty'),
('Geraldine James'),
('R. H. Thomson'),
('Corrine Koslo'),
('Dalila Bela'),
('Lucas Jade Zumann'),
('Gillian Anderson'),
('David Duchovny'),
('Mitch Pileggi'),
('Robert Patrick'),
('Tom Braidwood'),
('Bruce Harwood'),
('Jared Harris'),
('Stellan Skarsgård'),
('Emily Watson'),
('Paul Ritter'),
('Jessie Buckley'),
('Adam Nagaitis'),
('Evan Rachel Wood'),
('Thandie Newton'),
('Jeffrey Wright'),
('Tessa Thompson'),
('Ed Harris'),
('Luke Hemsworth'),
('Lee Pace'),
('Scoot McNairy'),
('Mackenzie Davis'),
('Kerry Bishé'),
('Toby Huss'),
('Alana Cavanaugh'),
('Jessica Chastain'),
('John Malkovich'),
('Colin Farrell'),
('Common'),
('Geena Davis'),
('Ioan Gruffudd'),
('Margot Robbie'),
('Ewan McGregor'),
('Mary Elizabeth Winstead'),
('Jurnee Smollett'),
('Rosie Perez'),
('Chris Messina'),
('Stacy Martin'),
('Rhona Mitra'),
('Theo James'),
('Peter Ferdinando'),
('Lia Williams'),
('Toby Jones'),
('Dwayne Johnson'),
('Kevin Hart'),
('Jack Black'),
('Karen Gillan'),
('Awkwafina'),
('Nick Jonas'),
('Miranda Cosgrove'),
('Kate Walsh'),
('Omar Epps'),
('Angus Macfadyen'),
('Jorja Fox'),
('Enver Gjokaj'),
('Bill Skarsgård'),
('Bill Hader'),
('James McAvoy'),
('Isaiah Mustafa'),
('Jay Ryan'),
('Chadwick Boseman'),
('Michael B. Jordan'),
('Lupita Nyong o'),
('Danai Gurira'),
('Martin Freeman'),
('Daniel Kaluuya'),
('Christian Bale'),
('Matt Damon'),
('Caitriona Balfe'),
('Josh Lucas'),
('Noah Jupe'),
('Jon Bernthal'),
('Génesis Rodríguez'),
('Vincent Piazza'),
('Benjamin Sokolow'),
('Emily Bayiokos'),
('Amy Manson'),
('Luke Allen-Gale'),
('Nina Bergman'),
('Dominic Mafham'),
('James Weber Brown'),
('Lorina Kamburova'),
('Marion Cotillard'),
('Laurence Fishburne'),
('Jude Law'),
('Kate Winslet'),
('Jennifer Ehle'),
('Gwyneth Paltrow'),
('Florence Pugh'),
('David Harbour'),
('O.T. Fagbenle'),
('Rachel Weisz'),
('William Hurt'),
('Ray Winstone'),
('Kristen Wiig'),
('Jeff Daniels'),
('Michael Peña'),
('Sean Bean'),
('Kate Mara'),
('Alicia Vikander'),
('Domhnall Gleeson'),
('Oscar Isaac'),
('Sonoya Mizuno'),
('Corey Johnson'),
('Claire Selby'),
('Gana Bayarsaikhan'),
('Bryce Dallas Howard'),
('Chris Pratt'),
('Irrfan Khan'),
('Vincent D''Onofrio'),
('Omar Sy'),
('Nick Robinson'),
('Judy Greer'),
('Will Smith'),
('Alice Braga'),
('Charlie Tahan'),
('Dash Mihok'),
('Salli Richardson-Whitfield'),
('Willow Smith'),
('Emma Thompson'),
('Ryan Gosling'),
('Claire Foy'),
('Jason Clarke'),
('Kyle Chandler'),
('Corey Stoll'),
('Patrick Fugit'),
('John Boyega'),
('Scott Eastwood'),
('Cailee Spaeny'),
('Jing Tian'),
('Rinko Kikuchi'),
('Burn Gorman');


-- Insertar datos en la tabla 'GENERO'
INSERT INTO GENERO (Nombre) VALUES
('Ciencia Ficción'),
('Fantasía'),
('Drama'),
('Ficción'),
('Sucesos'),
('Misterio'),
('Hechos verídicos'),
('Crimen'),
('Suspenso'),
('Aventura'),
('Comedia'),
('Familia'),
('Western'),
('Tecnología'),
('Acción'),
('Terror'),
('Historia'),
('Intriga'),
('Sci-Fi');

-- Insertar datos en la tabla 'CATALOGO'
INSERT INTO CATALOGO (Poster, Titulo, Categoria_id, Resumen, Temporadas, Trailer) VALUES
('/posters/3.jpg', 'The Mandalorian', 1, 'Ambientada tras la caída del Imperio...', 2, 'https://www.youtube.com/embed/aOC8E8z_ifw'),
('/posters/4.jpg', 'The Umbrella Academy', 1, 'La muerte de su padre reúne a unos hermanos...', 1, NULL),
('/posters/5.jpg', 'Gambito de Dama', 1, 'En los cincuenta, una joven de un orfanato...', 1, NULL),
('/posters/2.jpg', 'Riverdale', 1, 'El paso a la edad adulta incluye sexo, romance...', 5, NULL),
('/posters/1.jpg', 'The Crown', 1, 'Este drama narra las rivalidades políticas y el romance...', 4, NULL),
('/posters/6.jpg', 'Enola Holmes', 2, 'La hermana menor de Sherlock, descubre que su madre ha desaparecido...', NULL, NULL),
('/posters/7.jpg', 'Guasón', 2, 'Arthur Fleck (Phoenix) es un hombre ignorado por la sociedad...', NULL, 'https://www.youtube.com/embed/zAGVQLHvwOY'),
('/posters/8.jpg', 'Avengers: End Game', 2, 'Después de los devastadores eventos de los Vengadores: Infinity War...', NULL, NULL),
('/posters/9.jpg', 'Juego de tronos', 1, 'En un mundo fantástico y en un contexto medieval varias familias...', 8, NULL),
('/posters/10.jpg', 'The Flash', 1, 'Sigue las veloces aventuras de Barry Allen, un joven común...', 6, NULL),
('/posters/11.jpg', 'The Big Bang Theory', 1, 'Leonard y Sheldon son dos físicos que comparten trabajo y apartamento...', '12', 'https://www.youtube.com/embed/WBb3fojgW0Q'),
('/posters/12.jpg', 'Friends', 1, "'Friends' narra las aventuras y desventuras de seis jóvenes de Nueva York...", '10', ''),
('/posters/13.jpg', 'Anne with an ''E''', 1, 'Anne Shirley es una niña huérfana que vive en un pequeño pueblo llamado Avonlea...', '2', ''),
('/posters/14.jpg', 'Expedientes Secretos ''X''', 1, 'Fox Mulder y Dana Scully son dos investigadores del FBI que investigan casos sin resolución...', '11', 'https://www.youtube.com/embed/KKziOmsJxzE'),
('/posters/15.jpg', 'Chernobyl', 1, 'Sigue «la verdadera historia de una de las peores catástrofes provocadas por el hombre y habla de los valientes hombres y mujeres que se sacrificaron...', '1', 'https://www.youtube.com/embed/s9APLXM9Ei8'),
('/posters/16.jpg', 'Westworld', 1, "'Westworld' es una oscura odisea acerca del amanecer de la conciencia artificial y la evolución del pecado...", '3', 'https://www.youtube.com/embed/qLFBcdd6Qw0'),
('/posters/17.jpg', 'Halt and Catch Fire', 1, 'Situada en los inicios de la década de 1980, un visionario ficticio...', '4', 'https://www.youtube.com/embed/pWrioRji60A'),
('/posters/18.jpg', 'Ava', 2, 'Ava es una mortífera asesina a sueldo que trabaja para una organización de operaciones encubiertas...', 'N/A', ''),
('/posters/19.jpg', 'Aves de presa y la fantabulosa emancipación de una Harley Quinn', 2, 'Después de separarse de Joker, Harley Quinn y otras tres heroínas...', 'N/A', ''),
('/posters/20.jpg', 'Archivo', 1, '2038: George Almore está trabajando en una verdadera IA equivalente a la humana...', 'N/A', 'https://www.youtube.com/embed/VHSoCnDioAo'),
('/posters/21.jpg', 'Jumanji - The next level', 1, 'Las aventuras continúan en el fantástico mundo del video juego Jumanji...', 'N/A', 'https://www.youtube.com/embed/rBxcF-r9Ibs'),
('/posters/22.jpg', '3022', 1, 'La película está ambientada en una estación espacial en el futuro...', 'N/A', 'https://www.youtube.com/embed/AGQ7OkmIx4Q'),
('/posters/23.jpg', 'IT - Capítulo 2', 1, 'En este segundo capitulo Han pasado 27 años desde que el ''Club de los Perdedores''...', 'N/A', 'https://www.youtube.com/embed/hZeFeYSmBcg'),
('/posters/24.jpg', 'Pantera Negra', 1, 'T’Challa (Chadwick Boseman) regresa a su hogar en la apartada nación africana de Wakanda...', 'N/A', 'https://www.youtube.com/embed/BE6inv8Xh4A'),
('/posters/25.jpg', 'Contra lo imposible (Ford versus Ferrari)', 1, 'Los ganadores del Premio de la Academia® Matt Damon y Christian Bale protagonizan CONTRA LO IMPOSIBLE...', 'N/A', 'https://www.youtube.com/embed/SOVb0-2g1Q0'),
('/posters/26.jpg', 'Centígrados', 1, 'Una joven pareja estadounidense viaja a las montañas árticas de Noruega. Después de detenerse...', 'N/A', NULL),
('/posters/27.jpg', 'DOOM: Aniquilación', 1, 'Doom: Aniquilación sigue a un grupo de marines espaciales que han respondido a una llamada de alerta...', 'N/A', 'https://www.youtube.com/embed/nat3u3gAVLE'),
('/posters/28.jpg', 'Contagio', 1, 'De repente, sin saber cuál es su origen, aunque todo hace sospechar que comienza con el viaje...', 'N/A', 'https://www.youtube.com/embed/4sYSyuuLk5g'),
('/posters/29.jpg', 'Viuda Negra', 1, 'Primera pelicula individual de la Viuda Negra en el universo cinematografico de Marvel, contando...', 'N/A', 'https://www.youtube.com/embed/BIn8iANwEog'),
('/posters/30.jpg', 'The Martian', 1, 'Durante una misión a Marte de la nave tripulada Ares III, una fuerte tormenta se desata...', 'N/A', 'https://www.youtube.com/embed/XvB58bCVfng'),
('/posters/31.jpg', 'Ex-Machina', 1, 'Un programador multimillonario selecciona a Caleb, un joven empleado de su empresa, para que pase una semana en un lugar remoto...', 'N/A', 'https://www.youtube.com/embed/XRYL5spvEcI'),
('/posters/32.jpg', 'Jurassic World', 1, 'Veintidós años después de lo ocurrido en Jurassic Park, la isla Nublar ha sido transformada en un enorme parque temático...', 'N/A', NULL),
('/posters/33.jpg', 'Soy leyenda', 1, 'Años después de que una plaga mate a la mayoría de la humanidad y transforme al resto en monstruos...', 'N/A', 'https://www.youtube.com/embed/dtKMEAXyPkg'),
('/posters/34.jpg', 'El primer hombre en la luna', 1, 'Cuenta la historia de la misión de la NASA que llevó al primer hombre a la luna, centrada en Neil Armstrong...', 'N/A', NULL),
('/posters/35.jpg', 'Titanes del pacífico - La insurrección', 1, 'Han pasado 10 años tras la primera invasión que sufrió la humanidad, pero la lucha aún no ha terminado...', 'N/A', NULL);

-- Insertar datos en la tabla 'CATALOGO_REPARTO'

INSERT INTO CATALOGO_REPARTO (Catalogo_id, Actor_id) VALUES
(3, 1),
(3, 2),
(3, 3),
(3, 4),
(3, 5),
(3, 6),
(4, 7),
(4, 8),
(4, 9),
(4, 10),
(4, 11),
(4, 12),
(5, 13),
(5, 14),
(5, 15),
(5, 16),
(5, 17),
(5, 18),
(2, 19),
(2, 20),
(2, 21),
(2, 22),
(2, 23),
(2, 24),
(1, 25),
(1, 26),
(1, 27),
(1, 28),
(1, 29),
(1, 30),
(6, 31),
(6, 32),
(6, 33),
(6, 30),
(6, 34),
(6, 35),
(7, 36),
(7, 37),
(7, 38),
(7, 39),
(7, 40),
(7, 41),
(8, 42),
(8, 43),
(8, 44),
(8, 45),
(8, 46),
(8, 47),
(9, 48),
(9, 49),
(9, 50),
(9, 51),
(9, 52),
(9, 53),
(10, 54),
(10, 55),
(10, 56),
(10, 57),
(10, 58),
(10, 59),
(11, 60),
(11, 61),
(11, 62),
(11, 63),
(11, 64),
(11, 65),
(11, 66),
(12, 67),
(12, 68),
(12, 69),
(12, 70),
(12, 71),
(12, 72),
(13, 73),
(13, 74),
(13, 75),
(13, 76),
(13, 77),
(13, 78),
(14, 79),
(14, 80),
(14, 81),
(14, 82),
(14, 83),
(14, 84),
(15, 85),
(15, 86),
(15, 87),
(15, 88),
(15, 89),
(15, 90),
(16, 91),
(16, 92),
(16, 93),
(16, 94),
(16, 95),
(16, 96),
(17, 97),
(17, 98),
(17, 99),
(17, 100),
(17, 101),
(17, 102),
(18, 103),
(18, 104),
(18, 105),
(18, 106),
(18, 107),
(18, 108),
(19, 109),
(19, 110),
(19, 111),
(19, 112),
(19, 113),
(19, 114),
(20, 115),
(20, 116),
(20, 117),
(20, 118),
(20, 119),
(20, 120),
(21, 121),
(21, 122),
(21, 123),
(21, 124),
(21, 125),
(21, 126),
(22, 127),
(22, 128),
(22, 129),
(22, 130),
(22, 131),
(22, 132),
(23, 133),
(23, 103),
(23, 134),
(23, 135),
(23, 136),
(23, 137),
(24, 138),
(24, 139),
(24, 140),
(24, 141),
(24, 142),
(24, 143),
(25, 144),
(25, 145),
(25, 146),
(25, 147),
(25, 148),
(25, 149),
(26, 150),
(26, 151),
(26, 152),
(26, 153),
(27, 154),
(27, 155),
(27, 156),
(27, 157),
(27, 158),
(27, 159),
(28, 160),
(28, 145),
(28, 161),
(28, 162),
(28, 163),
(28, 164),
(28, 165),
(29, 46),
(29, 166),
(29, 167),
(29, 168),
(29, 169),
(29, 170),
(29, 171),
(30, 145),
(30, 103),
(30, 172),
(30, 173),
(30, 174),
(30, 175),
(30, 176),
(31, 177),
(31, 178),
(31, 179),
(31, 180),
(31, 181),
(31, 182),
(31, 183),
(32, 184),
(32, 185),
(32, 186),
(32, 187),
(32, 188),
(32, 189),
(32, 190),
(33, 191),
(33, 192),
(33, 193),
(33, 194),
(33, 195),
(33, 196),
(33, 197),
(34, 198),
(34, 199),
(34, 200),
(34, 201),
(34, 202),
(34, 203),
(35, 204),
(35, 205),
(35, 206),
(35, 207),
(35, 208),
(35, 209);



-- Insertar datos en la tabla 'CATALOGO_GENERO'

INSERT INTO CATALOGO_GENERO (Catalogo_id, Genero_id) VALUES
(3, 1),
(3, 2),
(4, 1),
(4, 2),
(5, 3),
(5, 4),
(5, 5),
(6, 4),
(6, 3),
(6, 6),
(7, 8),
(7, 9),
(7, 3),
(8, 10),
(8, 19),
(8, 15),
(9, 10),
(9, 2),
(9, 3),
(10, 1),
(10, 2),
(11, 11),
(11, 2),
(11, 4),
(12, 11),
(12, 12),
(12, 3),
(13, 3),
(13, 12),
(13, 13),
(14, 3),
(14, 1),
(15, 3),
(15, 7),
(16, 13),
(16, 1),
(17, 4),
(17, 3),
(17, 14),
(18, 15),
(18, 3),
(18, 9),
(19, 15),
(19, 4),
(19, 11),
(20, 15),
(20, 19),
(20, 9),
(21, 11),
(21, 4),
(21, 10),
(22, 1),
(22, 9),
(23, 16),
(23, 9),
(23, 2),
(24, 15),
(24, 10),
(24, 2),
(25, 3),
(25, 17),
(25, 10),
(26, 3),
(26, 9),
(26, 18),
(27, 15),
(27, 19),
(27, 16),
(28, 3),
(28, 9),
(28, 4),
(29, 3),
(29, 15),
(29, 10),
(30, 3),
(30, 19),
(30, 10),
(31, 3),
(31, 19),
(31, 9),
(32, 9),
(32, 10),
(32, 4),
(33, 3),
(33, 16),
(33, 4),
(34, 3),
(34, 7),
(35, 15),
(35, 2),
(35, 19);
